name: 发布 BiliScraper 到 release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Publish Python Package
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 编译打包为wheel文件
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: 获取Release版本号
        id: release_version
        run: |
          app_version=$(cat setup.py | grep version | sed "s/version='\([0-9]\+\.[0-9]\+\.[0-9]\+\)',/\1/" | sed s/[[:space:]]//g)
          echo "app_version=$app_version" >> $GITHUB_ENV
          echo "app_version=$app_version"

      - name: 上传二进制文件到release发布
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: v${{env.app_version}}
          release_name: v${{env.app_version}}
          overwrite: true
          file_glob: true
          body: ${{github.event.head_commit.message}}
